// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: department.proto

package department

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResp) Reset() {
	*x = ActionResp{}
	mi := &file_department_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResp) ProtoMessage() {}

func (x *ActionResp) ProtoReflect() protoreflect.Message {
	mi := &file_department_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResp.ProtoReflect.Descriptor instead.
func (*ActionResp) Descriptor() ([]byte, []int) {
	return file_department_proto_rawDescGZIP(), []int{0}
}

func (x *ActionResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ActionResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ActionResp) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type DepartmentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ParentId      int64                  `protobuf:"varint,4,opt,name=parentId,proto3" json:"parentId,omitempty"`
	CreateTime    string                 `protobuf:"bytes,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepartmentInfo) Reset() {
	*x = DepartmentInfo{}
	mi := &file_department_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepartmentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentInfo) ProtoMessage() {}

func (x *DepartmentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_department_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentInfo.ProtoReflect.Descriptor instead.
func (*DepartmentInfo) Descriptor() ([]byte, []int) {
	return file_department_proto_rawDescGZIP(), []int{1}
}

func (x *DepartmentInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DepartmentInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DepartmentInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DepartmentInfo) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *DepartmentInfo) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type DepartmentListData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*DepartmentInfo      `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepartmentListData) Reset() {
	*x = DepartmentListData{}
	mi := &file_department_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepartmentListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentListData) ProtoMessage() {}

func (x *DepartmentListData) ProtoReflect() protoreflect.Message {
	mi := &file_department_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentListData.ProtoReflect.Descriptor instead.
func (*DepartmentListData) Descriptor() ([]byte, []int) {
	return file_department_proto_rawDescGZIP(), []int{2}
}

func (x *DepartmentListData) GetList() []*DepartmentInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *DepartmentListData) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DepartmentListData) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *DepartmentListData) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type DepartmentListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *DepartmentListData    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepartmentListResp) Reset() {
	*x = DepartmentListResp{}
	mi := &file_department_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepartmentListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentListResp) ProtoMessage() {}

func (x *DepartmentListResp) ProtoReflect() protoreflect.Message {
	mi := &file_department_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentListResp.ProtoReflect.Descriptor instead.
func (*DepartmentListResp) Descriptor() ([]byte, []int) {
	return file_department_proto_rawDescGZIP(), []int{3}
}

func (x *DepartmentListResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DepartmentListResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *DepartmentListResp) GetData() *DepartmentListData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DepartmentListResp) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type DepartmentListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Auth          *DepartmentContext     `protobuf:"bytes,4,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepartmentListReq) Reset() {
	*x = DepartmentListReq{}
	mi := &file_department_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepartmentListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentListReq) ProtoMessage() {}

func (x *DepartmentListReq) ProtoReflect() protoreflect.Message {
	mi := &file_department_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentListReq.ProtoReflect.Descriptor instead.
func (*DepartmentListReq) Descriptor() ([]byte, []int) {
	return file_department_proto_rawDescGZIP(), []int{4}
}

func (x *DepartmentListReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *DepartmentListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *DepartmentListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *DepartmentListReq) GetAuth() *DepartmentContext {
	if x != nil {
		return x.Auth
	}
	return nil
}

type CreateDepartmentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ParentId      int64                  `protobuf:"varint,3,opt,name=parentId,proto3" json:"parentId,omitempty"`
	Auth          *DepartmentContext     `protobuf:"bytes,4,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDepartmentReq) Reset() {
	*x = CreateDepartmentReq{}
	mi := &file_department_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDepartmentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDepartmentReq) ProtoMessage() {}

func (x *CreateDepartmentReq) ProtoReflect() protoreflect.Message {
	mi := &file_department_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDepartmentReq.ProtoReflect.Descriptor instead.
func (*CreateDepartmentReq) Descriptor() ([]byte, []int) {
	return file_department_proto_rawDescGZIP(), []int{5}
}

func (x *CreateDepartmentReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateDepartmentReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateDepartmentReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CreateDepartmentReq) GetAuth() *DepartmentContext {
	if x != nil {
		return x.Auth
	}
	return nil
}

type UpdateDepartmentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ParentId      int64                  `protobuf:"varint,4,opt,name=parentId,proto3" json:"parentId,omitempty"`
	Auth          *DepartmentContext     `protobuf:"bytes,5,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDepartmentReq) Reset() {
	*x = UpdateDepartmentReq{}
	mi := &file_department_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDepartmentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDepartmentReq) ProtoMessage() {}

func (x *UpdateDepartmentReq) ProtoReflect() protoreflect.Message {
	mi := &file_department_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDepartmentReq.ProtoReflect.Descriptor instead.
func (*UpdateDepartmentReq) Descriptor() ([]byte, []int) {
	return file_department_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDepartmentReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDepartmentReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateDepartmentReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateDepartmentReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *UpdateDepartmentReq) GetAuth() *DepartmentContext {
	if x != nil {
		return x.Auth
	}
	return nil
}

type DeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           string                 `protobuf:"bytes,1,opt,name=ids,proto3" json:"ids,omitempty"`
	Auth          *DepartmentContext     `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReq) Reset() {
	*x = DeleteReq{}
	mi := &file_department_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReq) ProtoMessage() {}

func (x *DeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_department_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReq.ProtoReflect.Descriptor instead.
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return file_department_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteReq) GetIds() string {
	if x != nil {
		return x.Ids
	}
	return ""
}

func (x *DeleteReq) GetAuth() *DepartmentContext {
	if x != nil {
		return x.Auth
	}
	return nil
}

type DepartmentContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepartmentContext) Reset() {
	*x = DepartmentContext{}
	mi := &file_department_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepartmentContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentContext) ProtoMessage() {}

func (x *DepartmentContext) ProtoReflect() protoreflect.Message {
	mi := &file_department_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentContext.ProtoReflect.Descriptor instead.
func (*DepartmentContext) Descriptor() ([]byte, []int) {
	return file_department_proto_rawDescGZIP(), []int{8}
}

func (x *DepartmentContext) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DepartmentContext) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DepartmentContext) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_department_proto protoreflect.FileDescriptor

const file_department_proto_rawDesc = "" +
	"\n" +
	"\x10department.proto\x12\n" +
	"department\"P\n" +
	"\n" +
	"ActionResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x94\x01\n" +
	"\x0eDepartmentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bparentId\x18\x04 \x01(\x03R\bparentId\x12\x1e\n" +
	"\n" +
	"createTime\x18\x05 \x01(\tR\n" +
	"createTime\"\x8a\x01\n" +
	"\x12DepartmentListData\x12.\n" +
	"\x04list\x18\x01 \x03(\v2\x1a.department.DepartmentInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x03R\bpageSize\"\x8c\x01\n" +
	"\x12DepartmentListResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x122\n" +
	"\x04data\x18\x03 \x01(\v2\x1e.department.DepartmentListDataR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x90\x01\n" +
	"\x11DepartmentListReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\x121\n" +
	"\x04auth\x18\x04 \x01(\v2\x1d.department.DepartmentContextR\x04auth\"\x9c\x01\n" +
	"\x13CreateDepartmentReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bparentId\x18\x03 \x01(\x03R\bparentId\x121\n" +
	"\x04auth\x18\x04 \x01(\v2\x1d.department.DepartmentContextR\x04auth\"\xac\x01\n" +
	"\x13UpdateDepartmentReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bparentId\x18\x04 \x01(\x03R\bparentId\x121\n" +
	"\x04auth\x18\x05 \x01(\v2\x1d.department.DepartmentContextR\x04auth\"P\n" +
	"\tDeleteReq\x12\x10\n" +
	"\x03ids\x18\x01 \x01(\tR\x03ids\x121\n" +
	"\x04auth\x18\x02 \x01(\v2\x1d.department.DepartmentContextR\x04auth\"[\n" +
	"\x11DepartmentContext\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role2\x92\x02\n" +
	"\n" +
	"Department\x12E\n" +
	"\x04List\x12\x1d.department.DepartmentListReq\x1a\x1e.department.DepartmentListResp\x12A\n" +
	"\x06Create\x12\x1f.department.CreateDepartmentReq\x1a\x16.department.ActionResp\x12A\n" +
	"\x06Update\x12\x1f.department.UpdateDepartmentReq\x1a\x16.department.ActionResp\x127\n" +
	"\x06Delete\x12\x15.department.DeleteReq\x1a\x16.department.ActionRespB\x0eZ\f./departmentb\x06proto3"

var (
	file_department_proto_rawDescOnce sync.Once
	file_department_proto_rawDescData []byte
)

func file_department_proto_rawDescGZIP() []byte {
	file_department_proto_rawDescOnce.Do(func() {
		file_department_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_department_proto_rawDesc), len(file_department_proto_rawDesc)))
	})
	return file_department_proto_rawDescData
}

var file_department_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_department_proto_goTypes = []any{
	(*ActionResp)(nil),          // 0: department.ActionResp
	(*DepartmentInfo)(nil),      // 1: department.DepartmentInfo
	(*DepartmentListData)(nil),  // 2: department.DepartmentListData
	(*DepartmentListResp)(nil),  // 3: department.DepartmentListResp
	(*DepartmentListReq)(nil),   // 4: department.DepartmentListReq
	(*CreateDepartmentReq)(nil), // 5: department.CreateDepartmentReq
	(*UpdateDepartmentReq)(nil), // 6: department.UpdateDepartmentReq
	(*DeleteReq)(nil),           // 7: department.DeleteReq
	(*DepartmentContext)(nil),   // 8: department.DepartmentContext
}
var file_department_proto_depIdxs = []int32{
	1,  // 0: department.DepartmentListData.list:type_name -> department.DepartmentInfo
	2,  // 1: department.DepartmentListResp.data:type_name -> department.DepartmentListData
	8,  // 2: department.DepartmentListReq.auth:type_name -> department.DepartmentContext
	8,  // 3: department.CreateDepartmentReq.auth:type_name -> department.DepartmentContext
	8,  // 4: department.UpdateDepartmentReq.auth:type_name -> department.DepartmentContext
	8,  // 5: department.DeleteReq.auth:type_name -> department.DepartmentContext
	4,  // 6: department.Department.List:input_type -> department.DepartmentListReq
	5,  // 7: department.Department.Create:input_type -> department.CreateDepartmentReq
	6,  // 8: department.Department.Update:input_type -> department.UpdateDepartmentReq
	7,  // 9: department.Department.Delete:input_type -> department.DeleteReq
	3,  // 10: department.Department.List:output_type -> department.DepartmentListResp
	0,  // 11: department.Department.Create:output_type -> department.ActionResp
	0,  // 12: department.Department.Update:output_type -> department.ActionResp
	0,  // 13: department.Department.Delete:output_type -> department.ActionResp
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_department_proto_init() }
func file_department_proto_init() {
	if File_department_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_department_proto_rawDesc), len(file_department_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_department_proto_goTypes,
		DependencyIndexes: file_department_proto_depIdxs,
		MessageInfos:      file_department_proto_msgTypes,
	}.Build()
	File_department_proto = out.File
	file_department_proto_goTypes = nil
	file_department_proto_depIdxs = nil
}
