// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: oplog.proto

package server

import (
	"context"

	"oplog-service/internal/logic"
	"oplog-service/internal/svc"
	"oplog-service/oplog"
)

type OpLogServer struct {
	svcCtx *svc.ServiceContext
	oplog.UnimplementedOpLogServer
}

func NewOpLogServer(svcCtx *svc.ServiceContext) *OpLogServer {
	return &OpLogServer{
		svcCtx: svcCtx,
	}
}

func (s *OpLogServer) List(ctx context.Context, in *oplog.OpLogListReq) (*oplog.OpLogListResp, error) {
	l := logic.NewListLogic(ctx, s.svcCtx)
	return l.List(in)
}

func (s *OpLogServer) LoginList(ctx context.Context, in *oplog.OpLogListReq) (*oplog.OpLogListResp, error) {
	l := logic.NewLoginListLogic(ctx, s.svcCtx)
	return l.LoginList(in)
}

func (s *OpLogServer) BatchCreate(ctx context.Context, in *oplog.BatchCreateReq) (*oplog.ActionResp, error) {
	l := logic.NewBatchCreateLogic(ctx, s.svcCtx)
	return l.BatchCreate(in)
}
