services:
  # ==================== 单体业务 ====================
  go-server:
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: go_job_server
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      - upload_data:/app/uploads
      - ../api/etc/server-api-docker.yaml:/app/etc/server-api.yaml:ro
    networks:
      - app_net

  nginx:
    image: nginx:alpine
    container_name: go_job_nginx
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ../web/nginx.docker.conf:/etc/nginx/conf.d/default.conf:ro
      - ../web/dist:/usr/share/nginx/html:ro
    depends_on:
      - go-server
    networks:
      - app_net

  # ==================== 微服务业务 ====================
  user-service:
    build:
      context: .
      dockerfile: app/user-service/Dockerfile
    container_name: micro_user_service
    restart: unless-stopped
    ports:
      - "9101:9101"
    volumes:
      - ./app/user-service/etc/user.yaml:/app/etc/user.yaml:ro
    networks:
      - app_net

  department-service:
    build:
      context: .
      dockerfile: app/department-service/Dockerfile
    container_name: micro_department_service
    restart: unless-stopped
    ports:
      - "9102:9102"
    volumes:
      - ./app/department-service/etc/department.yaml:/app/etc/department.yaml:ro
    networks:
      - app_net

  oplog-service:
    build:
      context: .
      dockerfile: app/oplog-service/Dockerfile
    container_name: micro_oplog_service
    restart: unless-stopped
    ports:
      - "9103:9103"
    volumes:
      - ./app/oplog-service/etc/oplog.yaml:/app/etc/oplog.yaml:ro
    networks:
      - app_net

  api-gateway:
    build:
      context: .
      dockerfile: app/api-gateway/Dockerfile
    container_name: micro_api_gateway
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./app/api-gateway/etc/apigateway.yaml:/app/etc/apigateway.yaml:ro
    depends_on:
      - user-service
      - department-service
      - oplog-service
    networks:
      - app_net

volumes:
  upload_data:
    name: go_job_upload_data

networks:
  app_net:
    name: app_net
    external: true
