// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BDepartmentColumns holds the columns for the "b_department" table.
	BDepartmentColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString, Default: ""},
		{Name: "description", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "parent_id", Type: field.TypeInt, Nullable: true, Default: 0},
		{Name: "create_time", Type: field.TypeTime, Nullable: true},
	}
	// BDepartmentTable holds the schema information for the "b_department" table.
	BDepartmentTable = &schema.Table{
		Name:       "b_department",
		Columns:    BDepartmentColumns,
		PrimaryKey: []*schema.Column{BDepartmentColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BDepartmentTable,
	}
)

func init() {
}
