// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: oplog.proto

package opLogClient

import (
	"context"

	"oplog-service/oplog"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ActionResp     = oplog.ActionResp
	BatchCreateReq = oplog.BatchCreateReq
	OpLogContext   = oplog.OpLogContext
	OpLogInfo      = oplog.OpLogInfo
	OpLogListData  = oplog.OpLogListData
	OpLogListReq   = oplog.OpLogListReq
	OpLogListResp  = oplog.OpLogListResp
	OpLogRecord    = oplog.OpLogRecord

	OpLog interface {
		List(ctx context.Context, in *OpLogListReq, opts ...grpc.CallOption) (*OpLogListResp, error)
		LoginList(ctx context.Context, in *OpLogListReq, opts ...grpc.CallOption) (*OpLogListResp, error)
		BatchCreate(ctx context.Context, in *BatchCreateReq, opts ...grpc.CallOption) (*ActionResp, error)
	}

	defaultOpLog struct {
		cli zrpc.Client
	}
)

func NewOpLog(cli zrpc.Client) OpLog {
	return &defaultOpLog{
		cli: cli,
	}
}

func (m *defaultOpLog) List(ctx context.Context, in *OpLogListReq, opts ...grpc.CallOption) (*OpLogListResp, error) {
	client := oplog.NewOpLogClient(m.cli.Conn())
	return client.List(ctx, in, opts...)
}

func (m *defaultOpLog) LoginList(ctx context.Context, in *OpLogListReq, opts ...grpc.CallOption) (*OpLogListResp, error) {
	client := oplog.NewOpLogClient(m.cli.Conn())
	return client.LoginList(ctx, in, opts...)
}

func (m *defaultOpLog) BatchCreate(ctx context.Context, in *BatchCreateReq, opts ...grpc.CallOption) (*ActionResp, error) {
	client := oplog.NewOpLogClient(m.cli.Conn())
	return client.BatchCreate(ctx, in, opts...)
}
