// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type BaseResp struct {
	Code      int64  `json:"code"`
	Msg       string `json:"msg"`
	Trace     string `json:"trace,omitempty"`
	Timestamp int64  `json:"timestamp"`
}

type CreateDepartmentReq struct {
	Title       string `json:"title"`
	Description string `json:"description,optional"`
	ParentId    int64  `json:"parentId,optional"`
}

type CreateUserReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Nickname string `json:"nickname,optional"`
	Mobile   string `json:"mobile,optional"`
	Email    string `json:"email,optional"`
	Role     string `json:"role,optional"`
	Status   string `json:"status,optional"`
}

type CreateUserResp struct {
	BaseResp
}

type DeleteReq struct {
	Ids string `json:"ids"`
}

type DeleteUserResp struct {
	BaseResp
}

type DepartmentCreateResp struct {
	BaseResp
}

type DepartmentDeleteResp struct {
	BaseResp
}

type DepartmentInfo struct {
	Id          int64  `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	ParentId    int64  `json:"parentId"`
	CreateTime  string `json:"createTime"`
}

type DepartmentListData struct {
	List     []DepartmentInfo `json:"list"`
	Total    int64            `json:"total"`
	Page     int64            `json:"page"`
	PageSize int64            `json:"pageSize"`
}

type DepartmentListReq struct {
	Keyword  string `form:"keyword,optional"`
	Page     int64  `form:"page,optional,default=1"`
	PageSize int64  `form:"pageSize,optional,default=10"`
}

type DepartmentListResp struct {
	BaseResp
	Data *DepartmentListData `json:"data,omitempty"`
}

type UpdateDepartmentReq struct {
	Id          int64  `json:"id"`
	Title       string `json:"title,optional"`
	Description string `json:"description,optional"`
	ParentId    int64  `json:"parentId,optional"`
}

type DepartmentUpdateResp struct {
	BaseResp
}

type LoginLogListReq struct {
	Page     int64 `form:"page,optional,default=1"`
	PageSize int64 `form:"pageSize,optional,default=10"`
}

type LoginLogListResp struct {
	BaseResp
	Data *OpLogListData `json:"data,omitempty"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	BaseResp
	Data *UserInfo `json:"data,omitempty"`
}

type OpLogInfo struct {
	Id             string `json:"id"`
	RequestId      string `json:"requestId"`
	UserId         string `json:"userId"`
	ReIp           string `json:"reIp"`
	ReTime         string `json:"reTime"`
	ReUa           string `json:"reUa"`
	ReUrl          string `json:"reUrl"`
	ReMethod       string `json:"reMethod"`
	ReContent      string `json:"reContent"`
	Success        string `json:"success"`
	BizCode        int64  `json:"bizCode"`
	BizMsg         string `json:"bizMsg"`
	ReResponseTime string `json:"reResponseTime"`
	ReUserAgent    string `json:"reUserAgent"`
}

type OpLogListData struct {
	List     []OpLogInfo `json:"list"`
	Total    int64       `json:"total"`
	Page     int64       `json:"page"`
	PageSize int64       `json:"pageSize"`
}

type OpLogListReq struct {
	Page     int64 `form:"page,optional,default=1"`
	PageSize int64 `form:"pageSize,optional,default=10"`
}

type OpLogListResp struct {
	BaseResp
	Data *OpLogListData `json:"data,omitempty"`
}


type UpdatePwdReq struct {
	UserId      string `json:"userId"`
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type UpdatePwdResp struct {
	BaseResp
}

type UpdateUserInfoReq struct {
	Id       string `json:"id"`
	Nickname string `json:"nickname,optional"`
	Mobile   string `json:"mobile,optional"`
	Email    string `json:"email,optional"`
}

type UpdateUserInfoResp struct {
	BaseResp
}

type UpdateUserReq struct {
	Id       string `json:"id"`
	Username string `json:"username,optional"`
	Nickname string `json:"nickname,optional"`
	Mobile   string `json:"mobile,optional"`
	Email    string `json:"email,optional"`
	Role     string `json:"role,optional"`
	Status   string `json:"status,optional"`
	Password string `json:"password,optional"`
}

type UpdateUserResp struct {
	BaseResp
}

type UserDetailReq struct {
	UserId string `form:"userId"`
}

type UserDetailResp struct {
	BaseResp
	Data *UserInfo `json:"data,omitempty"`
}

type UserInfo struct {
	Id         string `json:"id"`
	Username   string `json:"username"`
	Password   string `json:"password"`
	Nickname   string `json:"nickname"`
	Mobile     string `json:"mobile"`
	Email      string `json:"email"`
	Role       string `json:"role"`
	Status     string `json:"status"`
	Token      string `json:"token"`
	CreateTime string `json:"createTime"`
	Avatar     string `json:"avatar,omitempty"`
}

type UserListData struct {
	List     []UserInfo `json:"list"`
	Total    int64      `json:"total"`
	Page     int64      `json:"page"`
	PageSize int64      `json:"pageSize"`
}

type UserListReq struct {
	Keyword  string `form:"keyword,optional"`
	Page     int64  `form:"page,optional,default=1"`
	PageSize int64  `form:"pageSize,optional,default=10"`
}

type UserListResp struct {
	BaseResp
	Data *UserListData `json:"data,omitempty"`
}

type UserLoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserLoginResp struct {
	BaseResp
	Data *UserInfo `json:"data,omitempty"`
}

type UserRegisterReq struct {
	Username   string `json:"username"`
	Password   string `json:"password"`
	RePassword string `json:"rePassword"`
	Nickname   string `json:"nickname,optional"`
	Mobile     string `json:"mobile,optional"`
	Email      string `json:"email,optional"`
}

type UserRegisterResp struct {
	BaseResp
}
