// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: oplog.proto

package oplog

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OpLog_List_FullMethodName        = "/oplog.OpLog/List"
	OpLog_LoginList_FullMethodName   = "/oplog.OpLog/LoginList"
	OpLog_BatchCreate_FullMethodName = "/oplog.OpLog/BatchCreate"
)

// OpLogClient is the client API for OpLog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpLogClient interface {
	List(ctx context.Context, in *OpLogListReq, opts ...grpc.CallOption) (*OpLogListResp, error)
	LoginList(ctx context.Context, in *OpLogListReq, opts ...grpc.CallOption) (*OpLogListResp, error)
	BatchCreate(ctx context.Context, in *BatchCreateReq, opts ...grpc.CallOption) (*ActionResp, error)
}

type opLogClient struct {
	cc grpc.ClientConnInterface
}

func NewOpLogClient(cc grpc.ClientConnInterface) OpLogClient {
	return &opLogClient{cc}
}

func (c *opLogClient) List(ctx context.Context, in *OpLogListReq, opts ...grpc.CallOption) (*OpLogListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpLogListResp)
	err := c.cc.Invoke(ctx, OpLog_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opLogClient) LoginList(ctx context.Context, in *OpLogListReq, opts ...grpc.CallOption) (*OpLogListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpLogListResp)
	err := c.cc.Invoke(ctx, OpLog_LoginList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opLogClient) BatchCreate(ctx context.Context, in *BatchCreateReq, opts ...grpc.CallOption) (*ActionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResp)
	err := c.cc.Invoke(ctx, OpLog_BatchCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpLogServer is the server API for OpLog service.
// All implementations must embed UnimplementedOpLogServer
// for forward compatibility.
type OpLogServer interface {
	List(context.Context, *OpLogListReq) (*OpLogListResp, error)
	LoginList(context.Context, *OpLogListReq) (*OpLogListResp, error)
	BatchCreate(context.Context, *BatchCreateReq) (*ActionResp, error)
	mustEmbedUnimplementedOpLogServer()
}

// UnimplementedOpLogServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOpLogServer struct{}

func (UnimplementedOpLogServer) List(context.Context, *OpLogListReq) (*OpLogListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedOpLogServer) LoginList(context.Context, *OpLogListReq) (*OpLogListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LoginList not implemented")
}
func (UnimplementedOpLogServer) BatchCreate(context.Context, *BatchCreateReq) (*ActionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchCreate not implemented")
}
func (UnimplementedOpLogServer) mustEmbedUnimplementedOpLogServer() {}
func (UnimplementedOpLogServer) testEmbeddedByValue()               {}

// UnsafeOpLogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpLogServer will
// result in compilation errors.
type UnsafeOpLogServer interface {
	mustEmbedUnimplementedOpLogServer()
}

func RegisterOpLogServer(s grpc.ServiceRegistrar, srv OpLogServer) {
	// If the following call panics, it indicates UnimplementedOpLogServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OpLog_ServiceDesc, srv)
}

func _OpLog_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpLogListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpLogServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpLog_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpLogServer).List(ctx, req.(*OpLogListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpLog_LoginList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpLogListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpLogServer).LoginList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpLog_LoginList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpLogServer).LoginList(ctx, req.(*OpLogListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpLog_BatchCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpLogServer).BatchCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpLog_BatchCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpLogServer).BatchCreate(ctx, req.(*BatchCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

// OpLog_ServiceDesc is the grpc.ServiceDesc for OpLog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OpLog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "oplog.OpLog",
	HandlerType: (*OpLogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _OpLog_List_Handler,
		},
		{
			MethodName: "LoginList",
			Handler:    _OpLog_LoginList_Handler,
		},
		{
			MethodName: "BatchCreate",
			Handler:    _OpLog_BatchCreate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oplog.proto",
}
