// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: oplog.proto

package oplog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResp) Reset() {
	*x = ActionResp{}
	mi := &file_oplog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResp) ProtoMessage() {}

func (x *ActionResp) ProtoReflect() protoreflect.Message {
	mi := &file_oplog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResp.ProtoReflect.Descriptor instead.
func (*ActionResp) Descriptor() ([]byte, []int) {
	return file_oplog_proto_rawDescGZIP(), []int{0}
}

func (x *ActionResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ActionResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ActionResp) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type OpLogContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpLogContext) Reset() {
	*x = OpLogContext{}
	mi := &file_oplog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpLogContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpLogContext) ProtoMessage() {}

func (x *OpLogContext) ProtoReflect() protoreflect.Message {
	mi := &file_oplog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpLogContext.ProtoReflect.Descriptor instead.
func (*OpLogContext) Descriptor() ([]byte, []int) {
	return file_oplog_proto_rawDescGZIP(), []int{1}
}

func (x *OpLogContext) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OpLogContext) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *OpLogContext) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type OpLogInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RequestId      string                 `protobuf:"bytes,2,opt,name=requestId,proto3" json:"requestId,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	ReIp           string                 `protobuf:"bytes,4,opt,name=reIp,proto3" json:"reIp,omitempty"`
	ReTime         string                 `protobuf:"bytes,5,opt,name=reTime,proto3" json:"reTime,omitempty"`
	ReUa           string                 `protobuf:"bytes,6,opt,name=reUa,proto3" json:"reUa,omitempty"`
	ReUrl          string                 `protobuf:"bytes,7,opt,name=reUrl,proto3" json:"reUrl,omitempty"`
	ReMethod       string                 `protobuf:"bytes,8,opt,name=reMethod,proto3" json:"reMethod,omitempty"`
	ReContent      string                 `protobuf:"bytes,9,opt,name=reContent,proto3" json:"reContent,omitempty"`
	Success        string                 `protobuf:"bytes,10,opt,name=success,proto3" json:"success,omitempty"`
	BizCode        int64                  `protobuf:"varint,11,opt,name=bizCode,proto3" json:"bizCode,omitempty"`
	BizMsg         string                 `protobuf:"bytes,12,opt,name=bizMsg,proto3" json:"bizMsg,omitempty"`
	AccessTime     string                 `protobuf:"bytes,13,opt,name=accessTime,proto3" json:"accessTime,omitempty"`
	ReResponseTime string                 `protobuf:"bytes,14,opt,name=reResponseTime,proto3" json:"reResponseTime,omitempty"`
	ReUserAgent    string                 `protobuf:"bytes,15,opt,name=reUserAgent,proto3" json:"reUserAgent,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OpLogInfo) Reset() {
	*x = OpLogInfo{}
	mi := &file_oplog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpLogInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpLogInfo) ProtoMessage() {}

func (x *OpLogInfo) ProtoReflect() protoreflect.Message {
	mi := &file_oplog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpLogInfo.ProtoReflect.Descriptor instead.
func (*OpLogInfo) Descriptor() ([]byte, []int) {
	return file_oplog_proto_rawDescGZIP(), []int{2}
}

func (x *OpLogInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OpLogInfo) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *OpLogInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OpLogInfo) GetReIp() string {
	if x != nil {
		return x.ReIp
	}
	return ""
}

func (x *OpLogInfo) GetReTime() string {
	if x != nil {
		return x.ReTime
	}
	return ""
}

func (x *OpLogInfo) GetReUa() string {
	if x != nil {
		return x.ReUa
	}
	return ""
}

func (x *OpLogInfo) GetReUrl() string {
	if x != nil {
		return x.ReUrl
	}
	return ""
}

func (x *OpLogInfo) GetReMethod() string {
	if x != nil {
		return x.ReMethod
	}
	return ""
}

func (x *OpLogInfo) GetReContent() string {
	if x != nil {
		return x.ReContent
	}
	return ""
}

func (x *OpLogInfo) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

func (x *OpLogInfo) GetBizCode() int64 {
	if x != nil {
		return x.BizCode
	}
	return 0
}

func (x *OpLogInfo) GetBizMsg() string {
	if x != nil {
		return x.BizMsg
	}
	return ""
}

func (x *OpLogInfo) GetAccessTime() string {
	if x != nil {
		return x.AccessTime
	}
	return ""
}

func (x *OpLogInfo) GetReResponseTime() string {
	if x != nil {
		return x.ReResponseTime
	}
	return ""
}

func (x *OpLogInfo) GetReUserAgent() string {
	if x != nil {
		return x.ReUserAgent
	}
	return ""
}

type OpLogListData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*OpLogInfo           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpLogListData) Reset() {
	*x = OpLogListData{}
	mi := &file_oplog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpLogListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpLogListData) ProtoMessage() {}

func (x *OpLogListData) ProtoReflect() protoreflect.Message {
	mi := &file_oplog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpLogListData.ProtoReflect.Descriptor instead.
func (*OpLogListData) Descriptor() ([]byte, []int) {
	return file_oplog_proto_rawDescGZIP(), []int{3}
}

func (x *OpLogListData) GetList() []*OpLogInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *OpLogListData) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *OpLogListData) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *OpLogListData) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type OpLogListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *OpLogListData         `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpLogListResp) Reset() {
	*x = OpLogListResp{}
	mi := &file_oplog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpLogListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpLogListResp) ProtoMessage() {}

func (x *OpLogListResp) ProtoReflect() protoreflect.Message {
	mi := &file_oplog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpLogListResp.ProtoReflect.Descriptor instead.
func (*OpLogListResp) Descriptor() ([]byte, []int) {
	return file_oplog_proto_rawDescGZIP(), []int{4}
}

func (x *OpLogListResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OpLogListResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *OpLogListResp) GetData() *OpLogListData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *OpLogListResp) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type OpLogListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Auth          *OpLogContext          `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpLogListReq) Reset() {
	*x = OpLogListReq{}
	mi := &file_oplog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpLogListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpLogListReq) ProtoMessage() {}

func (x *OpLogListReq) ProtoReflect() protoreflect.Message {
	mi := &file_oplog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpLogListReq.ProtoReflect.Descriptor instead.
func (*OpLogListReq) Descriptor() ([]byte, []int) {
	return file_oplog_proto_rawDescGZIP(), []int{5}
}

func (x *OpLogListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *OpLogListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *OpLogListReq) GetAuth() *OpLogContext {
	if x != nil {
		return x.Auth
	}
	return nil
}

type OpLogRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	ReIp          string                 `protobuf:"bytes,3,opt,name=reIp,proto3" json:"reIp,omitempty"`
	ReTime        int64                  `protobuf:"varint,4,opt,name=reTime,proto3" json:"reTime,omitempty"`
	ReUa          string                 `protobuf:"bytes,5,opt,name=reUa,proto3" json:"reUa,omitempty"`
	ReUrl         string                 `protobuf:"bytes,6,opt,name=reUrl,proto3" json:"reUrl,omitempty"`
	ReMethod      string                 `protobuf:"bytes,7,opt,name=reMethod,proto3" json:"reMethod,omitempty"`
	ReContent     string                 `protobuf:"bytes,8,opt,name=reContent,proto3" json:"reContent,omitempty"`
	Success       string                 `protobuf:"bytes,9,opt,name=success,proto3" json:"success,omitempty"`
	BizCode       int64                  `protobuf:"varint,10,opt,name=bizCode,proto3" json:"bizCode,omitempty"`
	BizMsg        string                 `protobuf:"bytes,11,opt,name=bizMsg,proto3" json:"bizMsg,omitempty"`
	AccessTime    int64                  `protobuf:"varint,12,opt,name=accessTime,proto3" json:"accessTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpLogRecord) Reset() {
	*x = OpLogRecord{}
	mi := &file_oplog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpLogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpLogRecord) ProtoMessage() {}

func (x *OpLogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_oplog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpLogRecord.ProtoReflect.Descriptor instead.
func (*OpLogRecord) Descriptor() ([]byte, []int) {
	return file_oplog_proto_rawDescGZIP(), []int{6}
}

func (x *OpLogRecord) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *OpLogRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OpLogRecord) GetReIp() string {
	if x != nil {
		return x.ReIp
	}
	return ""
}

func (x *OpLogRecord) GetReTime() int64 {
	if x != nil {
		return x.ReTime
	}
	return 0
}

func (x *OpLogRecord) GetReUa() string {
	if x != nil {
		return x.ReUa
	}
	return ""
}

func (x *OpLogRecord) GetReUrl() string {
	if x != nil {
		return x.ReUrl
	}
	return ""
}

func (x *OpLogRecord) GetReMethod() string {
	if x != nil {
		return x.ReMethod
	}
	return ""
}

func (x *OpLogRecord) GetReContent() string {
	if x != nil {
		return x.ReContent
	}
	return ""
}

func (x *OpLogRecord) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

func (x *OpLogRecord) GetBizCode() int64 {
	if x != nil {
		return x.BizCode
	}
	return 0
}

func (x *OpLogRecord) GetBizMsg() string {
	if x != nil {
		return x.BizMsg
	}
	return ""
}

func (x *OpLogRecord) GetAccessTime() int64 {
	if x != nil {
		return x.AccessTime
	}
	return 0
}

type BatchCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*OpLogRecord         `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateReq) Reset() {
	*x = BatchCreateReq{}
	mi := &file_oplog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateReq) ProtoMessage() {}

func (x *BatchCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_oplog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateReq.ProtoReflect.Descriptor instead.
func (*BatchCreateReq) Descriptor() ([]byte, []int) {
	return file_oplog_proto_rawDescGZIP(), []int{7}
}

func (x *BatchCreateReq) GetLogs() []*OpLogRecord {
	if x != nil {
		return x.Logs
	}
	return nil
}

var File_oplog_proto protoreflect.FileDescriptor

const file_oplog_proto_rawDesc = "" +
	"\n" +
	"\voplog.proto\x12\x05oplog\"P\n" +
	"\n" +
	"ActionResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"V\n" +
	"\fOpLogContext\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"\x97\x03\n" +
	"\tOpLogInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\trequestId\x18\x02 \x01(\tR\trequestId\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04reIp\x18\x04 \x01(\tR\x04reIp\x12\x16\n" +
	"\x06reTime\x18\x05 \x01(\tR\x06reTime\x12\x12\n" +
	"\x04reUa\x18\x06 \x01(\tR\x04reUa\x12\x14\n" +
	"\x05reUrl\x18\a \x01(\tR\x05reUrl\x12\x1a\n" +
	"\breMethod\x18\b \x01(\tR\breMethod\x12\x1c\n" +
	"\treContent\x18\t \x01(\tR\treContent\x12\x18\n" +
	"\asuccess\x18\n" +
	" \x01(\tR\asuccess\x12\x18\n" +
	"\abizCode\x18\v \x01(\x03R\abizCode\x12\x16\n" +
	"\x06bizMsg\x18\f \x01(\tR\x06bizMsg\x12\x1e\n" +
	"\n" +
	"accessTime\x18\r \x01(\tR\n" +
	"accessTime\x12&\n" +
	"\x0ereResponseTime\x18\x0e \x01(\tR\x0ereResponseTime\x12 \n" +
	"\vreUserAgent\x18\x0f \x01(\tR\vreUserAgent\"{\n" +
	"\rOpLogListData\x12$\n" +
	"\x04list\x18\x01 \x03(\v2\x10.oplog.OpLogInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x03R\bpageSize\"}\n" +
	"\rOpLogListResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.oplog.OpLogListDataR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"g\n" +
	"\fOpLogListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\x12'\n" +
	"\x04auth\x18\x03 \x01(\v2\x13.oplog.OpLogContextR\x04auth\"\xbf\x02\n" +
	"\vOpLogRecord\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04reIp\x18\x03 \x01(\tR\x04reIp\x12\x16\n" +
	"\x06reTime\x18\x04 \x01(\x03R\x06reTime\x12\x12\n" +
	"\x04reUa\x18\x05 \x01(\tR\x04reUa\x12\x14\n" +
	"\x05reUrl\x18\x06 \x01(\tR\x05reUrl\x12\x1a\n" +
	"\breMethod\x18\a \x01(\tR\breMethod\x12\x1c\n" +
	"\treContent\x18\b \x01(\tR\treContent\x12\x18\n" +
	"\asuccess\x18\t \x01(\tR\asuccess\x12\x18\n" +
	"\abizCode\x18\n" +
	" \x01(\x03R\abizCode\x12\x16\n" +
	"\x06bizMsg\x18\v \x01(\tR\x06bizMsg\x12\x1e\n" +
	"\n" +
	"accessTime\x18\f \x01(\x03R\n" +
	"accessTime\"8\n" +
	"\x0eBatchCreateReq\x12&\n" +
	"\x04logs\x18\x01 \x03(\v2\x12.oplog.OpLogRecordR\x04logs2\xab\x01\n" +
	"\x05OpLog\x121\n" +
	"\x04List\x12\x13.oplog.OpLogListReq\x1a\x14.oplog.OpLogListResp\x126\n" +
	"\tLoginList\x12\x13.oplog.OpLogListReq\x1a\x14.oplog.OpLogListResp\x127\n" +
	"\vBatchCreate\x12\x15.oplog.BatchCreateReq\x1a\x11.oplog.ActionRespB\tZ\a./oplogb\x06proto3"

var (
	file_oplog_proto_rawDescOnce sync.Once
	file_oplog_proto_rawDescData []byte
)

func file_oplog_proto_rawDescGZIP() []byte {
	file_oplog_proto_rawDescOnce.Do(func() {
		file_oplog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oplog_proto_rawDesc), len(file_oplog_proto_rawDesc)))
	})
	return file_oplog_proto_rawDescData
}

var file_oplog_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_oplog_proto_goTypes = []any{
	(*ActionResp)(nil),     // 0: oplog.ActionResp
	(*OpLogContext)(nil),   // 1: oplog.OpLogContext
	(*OpLogInfo)(nil),      // 2: oplog.OpLogInfo
	(*OpLogListData)(nil),  // 3: oplog.OpLogListData
	(*OpLogListResp)(nil),  // 4: oplog.OpLogListResp
	(*OpLogListReq)(nil),   // 5: oplog.OpLogListReq
	(*OpLogRecord)(nil),    // 6: oplog.OpLogRecord
	(*BatchCreateReq)(nil), // 7: oplog.BatchCreateReq
}
var file_oplog_proto_depIdxs = []int32{
	2, // 0: oplog.OpLogListData.list:type_name -> oplog.OpLogInfo
	3, // 1: oplog.OpLogListResp.data:type_name -> oplog.OpLogListData
	1, // 2: oplog.OpLogListReq.auth:type_name -> oplog.OpLogContext
	6, // 3: oplog.BatchCreateReq.logs:type_name -> oplog.OpLogRecord
	5, // 4: oplog.OpLog.List:input_type -> oplog.OpLogListReq
	5, // 5: oplog.OpLog.LoginList:input_type -> oplog.OpLogListReq
	7, // 6: oplog.OpLog.BatchCreate:input_type -> oplog.BatchCreateReq
	4, // 7: oplog.OpLog.List:output_type -> oplog.OpLogListResp
	4, // 8: oplog.OpLog.LoginList:output_type -> oplog.OpLogListResp
	0, // 9: oplog.OpLog.BatchCreate:output_type -> oplog.ActionResp
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_oplog_proto_init() }
func file_oplog_proto_init() {
	if File_oplog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oplog_proto_rawDesc), len(file_oplog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oplog_proto_goTypes,
		DependencyIndexes: file_oplog_proto_depIdxs,
		MessageInfos:      file_oplog_proto_msgTypes,
	}.Build()
	File_oplog_proto = out.File
	file_oplog_proto_goTypes = nil
	file_oplog_proto_depIdxs = nil
}
