// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: department.proto

package server

import (
	"context"

	"department-service/department"
	"department-service/internal/logic"
	"department-service/internal/svc"
)

type DepartmentServer struct {
	svcCtx *svc.ServiceContext
	department.UnimplementedDepartmentServer
}

func NewDepartmentServer(svcCtx *svc.ServiceContext) *DepartmentServer {
	return &DepartmentServer{
		svcCtx: svcCtx,
	}
}

func (s *DepartmentServer) List(ctx context.Context, in *department.DepartmentListReq) (*department.DepartmentListResp, error) {
	l := logic.NewListLogic(ctx, s.svcCtx)
	return l.List(in)
}

func (s *DepartmentServer) Create(ctx context.Context, in *department.CreateDepartmentReq) (*department.ActionResp, error) {
	l := logic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}

func (s *DepartmentServer) Update(ctx context.Context, in *department.UpdateDepartmentReq) (*department.ActionResp, error) {
	l := logic.NewUpdateLogic(ctx, s.svcCtx)
	return l.Update(in)
}

func (s *DepartmentServer) Delete(ctx context.Context, in *department.DeleteReq) (*department.ActionResp, error) {
	l := logic.NewDeleteLogic(ctx, s.svcCtx)
	return l.Delete(in)
}
