// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: department.proto

package departmentClient

import (
	"context"

	"department-service/department"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ActionResp          = department.ActionResp
	CreateDepartmentReq = department.CreateDepartmentReq
	DeleteReq           = department.DeleteReq
	DepartmentContext   = department.DepartmentContext
	DepartmentInfo      = department.DepartmentInfo
	DepartmentListData  = department.DepartmentListData
	DepartmentListReq   = department.DepartmentListReq
	DepartmentListResp  = department.DepartmentListResp
	UpdateDepartmentReq = department.UpdateDepartmentReq

	Department interface {
		List(ctx context.Context, in *DepartmentListReq, opts ...grpc.CallOption) (*DepartmentListResp, error)
		Create(ctx context.Context, in *CreateDepartmentReq, opts ...grpc.CallOption) (*ActionResp, error)
		Update(ctx context.Context, in *UpdateDepartmentReq, opts ...grpc.CallOption) (*ActionResp, error)
		Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*ActionResp, error)
	}

	defaultDepartment struct {
		cli zrpc.Client
	}
)

func NewDepartment(cli zrpc.Client) Department {
	return &defaultDepartment{
		cli: cli,
	}
}

func (m *defaultDepartment) List(ctx context.Context, in *DepartmentListReq, opts ...grpc.CallOption) (*DepartmentListResp, error) {
	client := department.NewDepartmentClient(m.cli.Conn())
	return client.List(ctx, in, opts...)
}

func (m *defaultDepartment) Create(ctx context.Context, in *CreateDepartmentReq, opts ...grpc.CallOption) (*ActionResp, error) {
	client := department.NewDepartmentClient(m.cli.Conn())
	return client.Create(ctx, in, opts...)
}

func (m *defaultDepartment) Update(ctx context.Context, in *UpdateDepartmentReq, opts ...grpc.CallOption) (*ActionResp, error) {
	client := department.NewDepartmentClient(m.cli.Conn())
	return client.Update(ctx, in, opts...)
}

func (m *defaultDepartment) Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*ActionResp, error) {
	client := department.NewDepartmentClient(m.cli.Conn())
	return client.Delete(ctx, in, opts...)
}
