// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type ApiResponse struct {
	Code      int64       `json:"code"`
	Msg       string      `json:"msg"`
	Data      interface{} `json:"data,optional"`
	Timestamp int64       `json:"timestamp"`
}

type CreateUserReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Nickname string `json:"nickname,optional"`
	Mobile   string `json:"mobile,optional"`
	Email    string `json:"email,optional"`
	Role     string `json:"role,optional"`
	Status   string `json:"status,optional"`
}

type DeleteReq struct {
	Ids string `json:"ids"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UpdatePwdReq struct {
	UserId      string `json:"userId"`
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type UpdateUserInfoReq struct {
	Id         string `json:"id"`
	Nickname   string `json:"nickname,optional"`
	Mobile     string `json:"mobile,optional"`
	Email      string `json:"email,optional"`
	PushEmail  string `json:"pushEmail,optional"`
	PushSwitch string `json:"pushSwitch,optional"`
}

type UpdateUserReq struct {
	Id         string `json:"id"`
	Username   string `json:"username,optional"`
	Nickname   string `json:"nickname,optional"`
	Mobile     string `json:"mobile,optional"`
	Email      string `json:"email,optional"`
	Role       string `json:"role,optional"`
	Status     string `json:"status,optional"`
	Password   string `json:"password,optional"`
	PushEmail  string `json:"pushEmail,optional"`
	PushSwitch string `json:"pushSwitch,optional"`
}

type UserDetailReq struct {
	UserId string `form:"userId"`
}

type UserListReq struct {
	Keyword  string `form:"keyword,optional"`
	Page     int64  `form:"page,optional,default=1"`
	PageSize int64  `form:"pageSize,optional,default=10"`
}

type UserLoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserRegisterReq struct {
	Username   string `json:"username"`
	Password   string `json:"password"`
	RePassword string `json:"rePassword"`
	Nickname   string `json:"nickname,optional"`
	Mobile     string `json:"mobile,optional"`
	Email      string `json:"email,optional"`
}
