// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package server

import (
	"context"

	logic "user-service/internal/logic/user"
	"user-service/internal/svc"
	"user-service/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// 无鉴权
func (s *UserServer) Login(ctx context.Context, in *user.LoginReq) (*user.UserInfoResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) UserLogin(ctx context.Context, in *user.UserLoginReq) (*user.UserInfoResp, error) {
	l := logic.NewUserLoginLogic(ctx, s.svcCtx)
	return l.UserLogin(in)
}

func (s *UserServer) Register(ctx context.Context, in *user.RegisterReq) (*user.ActionResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

// 需鉴权（api-gateway 透传 UserContext）
func (s *UserServer) Detail(ctx context.Context, in *user.IdReq) (*user.UserInfoResp, error) {
	l := logic.NewDetailLogic(ctx, s.svcCtx)
	return l.Detail(in)
}

func (s *UserServer) List(ctx context.Context, in *user.UserListReq) (*user.UserListResp, error) {
	l := logic.NewListLogic(ctx, s.svcCtx)
	return l.List(in)
}

func (s *UserServer) Create(ctx context.Context, in *user.CreateUserReq) (*user.ActionResp, error) {
	l := logic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}

func (s *UserServer) Update(ctx context.Context, in *user.UpdateUserReq) (*user.ActionResp, error) {
	l := logic.NewUpdateLogic(ctx, s.svcCtx)
	return l.Update(in)
}

func (s *UserServer) Delete(ctx context.Context, in *user.DeleteReq) (*user.ActionResp, error) {
	l := logic.NewDeleteLogic(ctx, s.svcCtx)
	return l.Delete(in)
}

func (s *UserServer) UpdateUserInfo(ctx context.Context, in *user.UpdateUserInfoReq) (*user.ActionResp, error) {
	l := logic.NewUpdateUserInfoLogic(ctx, s.svcCtx)
	return l.UpdateUserInfo(in)
}

func (s *UserServer) UpdatePwd(ctx context.Context, in *user.UpdatePwdReq) (*user.ActionResp, error) {
	l := logic.NewUpdatePwdLogic(ctx, s.svcCtx)
	return l.UpdatePwd(in)
}
