// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	department "api-gateway/internal/handler/department"
	user "api-gateway/internal/handler/user"
	"api-gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 管理员-创建部门
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: department.DepartmentCreateHandler(serverCtx),
			},
			{
				// 管理员-删除部门
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: department.DepartmentDeleteHandler(serverCtx),
			},
			{
				// 部门列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: department.DepartmentListHandler(serverCtx),
			},
			{
				// 管理员-更新部门
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: department.DepartmentUpdateHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JWT.AccessSecret),
		rest.WithPrefix("/api/department"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 管理员登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.UserLoginHandler(serverCtx),
			},
			{
				// 前台用户登录
				Method:  http.MethodPost,
				Path:    "/userLogin",
				Handler: user.UserUserLoginHandler(serverCtx),
			},
			{
				// 用户注册
				Method:  http.MethodPost,
				Path:    "/userRegister",
				Handler: user.UserRegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 管理员-创建用户
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: user.UserCreateHandler(serverCtx),
			},
			{
				// 管理员-删除用户
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: user.UserDeleteHandler(serverCtx),
			},
			{
				// 用户详情
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: user.UserDetailHandler(serverCtx),
			},
			{
				// 用户列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: user.UserListHandler(serverCtx),
			},
			{
				// 管理员-更新用户
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: user.UserUpdateHandler(serverCtx),
			},
			{
				// 用户-修改密码
				Method:  http.MethodPost,
				Path:    "/updatePwd",
				Handler: user.UserUpdatePwdHandler(serverCtx),
			},
			{
				// 用户-更新信息
				Method:  http.MethodPost,
				Path:    "/updateUserInfo",
				Handler: user.UserUpdateUserInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JWT.AccessSecret),
		rest.WithPrefix("/api/user"),
	)
}
