// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"department-service/ent/department"
	"department-service/ent/predicate"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DepartmentUpdate is the builder for updating Department entities.
type DepartmentUpdate struct {
	config
	hooks    []Hook
	mutation *DepartmentMutation
}

// Where appends a list predicates to the DepartmentUpdate builder.
func (_u *DepartmentUpdate) Where(ps ...predicate.Department) *DepartmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *DepartmentUpdate) SetTitle(v string) *DepartmentUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *DepartmentUpdate) SetNillableTitle(v *string) *DepartmentUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *DepartmentUpdate) SetDescription(v string) *DepartmentUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DepartmentUpdate) SetNillableDescription(v *string) *DepartmentUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *DepartmentUpdate) ClearDescription() *DepartmentUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *DepartmentUpdate) SetParentID(v int) *DepartmentUpdate {
	_u.mutation.ResetParentID()
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *DepartmentUpdate) SetNillableParentID(v *int) *DepartmentUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// AddParentID adds value to the "parent_id" field.
func (_u *DepartmentUpdate) AddParentID(v int) *DepartmentUpdate {
	_u.mutation.AddParentID(v)
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *DepartmentUpdate) ClearParentID() *DepartmentUpdate {
	_u.mutation.ClearParentID()
	return _u
}

// SetCreateTime sets the "create_time" field.
func (_u *DepartmentUpdate) SetCreateTime(v time.Time) *DepartmentUpdate {
	_u.mutation.SetCreateTime(v)
	return _u
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_u *DepartmentUpdate) SetNillableCreateTime(v *time.Time) *DepartmentUpdate {
	if v != nil {
		_u.SetCreateTime(*v)
	}
	return _u
}

// ClearCreateTime clears the value of the "create_time" field.
func (_u *DepartmentUpdate) ClearCreateTime() *DepartmentUpdate {
	_u.mutation.ClearCreateTime()
	return _u
}

// Mutation returns the DepartmentMutation object of the builder.
func (_u *DepartmentUpdate) Mutation() *DepartmentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DepartmentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DepartmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DepartmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DepartmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *DepartmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(department.Table, department.Columns, sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(department.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(department.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(department.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(department.FieldParentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedParentID(); ok {
		_spec.AddField(department.FieldParentID, field.TypeInt, value)
	}
	if _u.mutation.ParentIDCleared() {
		_spec.ClearField(department.FieldParentID, field.TypeInt)
	}
	if value, ok := _u.mutation.CreateTime(); ok {
		_spec.SetField(department.FieldCreateTime, field.TypeTime, value)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(department.FieldCreateTime, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{department.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DepartmentUpdateOne is the builder for updating a single Department entity.
type DepartmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DepartmentMutation
}

// SetTitle sets the "title" field.
func (_u *DepartmentUpdateOne) SetTitle(v string) *DepartmentUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *DepartmentUpdateOne) SetNillableTitle(v *string) *DepartmentUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *DepartmentUpdateOne) SetDescription(v string) *DepartmentUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DepartmentUpdateOne) SetNillableDescription(v *string) *DepartmentUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *DepartmentUpdateOne) ClearDescription() *DepartmentUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *DepartmentUpdateOne) SetParentID(v int) *DepartmentUpdateOne {
	_u.mutation.ResetParentID()
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *DepartmentUpdateOne) SetNillableParentID(v *int) *DepartmentUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// AddParentID adds value to the "parent_id" field.
func (_u *DepartmentUpdateOne) AddParentID(v int) *DepartmentUpdateOne {
	_u.mutation.AddParentID(v)
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *DepartmentUpdateOne) ClearParentID() *DepartmentUpdateOne {
	_u.mutation.ClearParentID()
	return _u
}

// SetCreateTime sets the "create_time" field.
func (_u *DepartmentUpdateOne) SetCreateTime(v time.Time) *DepartmentUpdateOne {
	_u.mutation.SetCreateTime(v)
	return _u
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_u *DepartmentUpdateOne) SetNillableCreateTime(v *time.Time) *DepartmentUpdateOne {
	if v != nil {
		_u.SetCreateTime(*v)
	}
	return _u
}

// ClearCreateTime clears the value of the "create_time" field.
func (_u *DepartmentUpdateOne) ClearCreateTime() *DepartmentUpdateOne {
	_u.mutation.ClearCreateTime()
	return _u
}

// Mutation returns the DepartmentMutation object of the builder.
func (_u *DepartmentUpdateOne) Mutation() *DepartmentMutation {
	return _u.mutation
}

// Where appends a list predicates to the DepartmentUpdate builder.
func (_u *DepartmentUpdateOne) Where(ps ...predicate.Department) *DepartmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DepartmentUpdateOne) Select(field string, fields ...string) *DepartmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Department entity.
func (_u *DepartmentUpdateOne) Save(ctx context.Context) (*Department, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DepartmentUpdateOne) SaveX(ctx context.Context) *Department {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DepartmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DepartmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *DepartmentUpdateOne) sqlSave(ctx context.Context) (_node *Department, err error) {
	_spec := sqlgraph.NewUpdateSpec(department.Table, department.Columns, sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Department.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, department.FieldID)
		for _, f := range fields {
			if !department.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != department.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(department.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(department.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(department.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(department.FieldParentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedParentID(); ok {
		_spec.AddField(department.FieldParentID, field.TypeInt, value)
	}
	if _u.mutation.ParentIDCleared() {
		_spec.ClearField(department.FieldParentID, field.TypeInt)
	}
	if value, ok := _u.mutation.CreateTime(); ok {
		_spec.SetField(department.FieldCreateTime, field.TypeTime, value)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(department.FieldCreateTime, field.TypeTime)
	}
	_node = &Department{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{department.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
