// Code generated by ent, DO NOT EDIT.

package ent

import (
	"department-service/ent/department"
	"department-service/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	departmentFields := schema.Department{}.Fields()
	_ = departmentFields
	// departmentDescTitle is the schema descriptor for title field.
	departmentDescTitle := departmentFields[1].Descriptor()
	// department.DefaultTitle holds the default value on creation for the title field.
	department.DefaultTitle = departmentDescTitle.Default.(string)
	// departmentDescDescription is the schema descriptor for description field.
	departmentDescDescription := departmentFields[2].Descriptor()
	// department.DefaultDescription holds the default value on creation for the description field.
	department.DefaultDescription = departmentDescDescription.Default.(string)
	// departmentDescParentID is the schema descriptor for parent_id field.
	departmentDescParentID := departmentFields[3].Descriptor()
	// department.DefaultParentID holds the default value on creation for the parent_id field.
	department.DefaultParentID = departmentDescParentID.Default.(int)
	// departmentDescCreateTime is the schema descriptor for create_time field.
	departmentDescCreateTime := departmentFields[4].Descriptor()
	// department.DefaultCreateTime holds the default value on creation for the create_time field.
	department.DefaultCreateTime = departmentDescCreateTime.Default.(func() time.Time)
}
